apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  name: db-secret
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: eks/ava-server
      versionId: f5725f90-490a-4cb3-9595-ddce7d7608cc
