apiVersion: v1
kind: Service
metadata:
  name: activemq-service
spec:
  selector:
    app: activemq
  ports:
    - protocol: TCP
      port: 61616 #JMS broker
      targetPort: 61616 
  type: ClusterIP
---

apiVersion: v1
kind: Service
metadata:
  name: activemq-web-console
spec:
  selector:
    app: activemq
  ports:
    - protocol: TCP
      port: 8161 #ActiveMQ web console
      targetPort: 8161 
  type: LoadBalancer