apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ava-server
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: ava-sever
    server: 'https://kubernetes.default.svc'
  source:
    path: ./k8-resources/app-deployments/
    repoURL: 'git@github.com:EatWithAva/dvelop-infrastructure.git'
    targetRevision: master
    directory:
      recurse: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
