apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-addons(nlb)
spec:
  destination:
    name: ''
    namespace: ingress-nginx
    server: 'https://kubernetes.default.svc'
  source:
    path: ./k8-resources/cluster-addons
    repoURL: 'git@github.com:EatWithAva/dvelop-infrastructure.git'
    targetRevision: master
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
