name: Terraform Workflow

on:
  push:
    branches:
      - master

jobs:
  Check-Commit-For-Infra-Workflow:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Commit Messages
        id: commit_check
        run: |
          commit_message=$(git log --format=%B -n 1 ${{ github.sha }})
          echo "Commit Message: $commit_message"
          if [[ "$commit_message" == *"destroy infra"* ]]; then
            gh workflow run terraform-destroy.yaml
          else
            gh workflow run terraform.yaml
          fi

