name: Terraform Workflow

on:
  push:
    branches:
      - master

jobs:
  check_commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check Commit Messages
        id: commit_check
        run: |
          commit_message=$(git log --format=%B -n 1 ${{ github.sha }})
          echo "Commit Message: $commit_message"
          if [[ "$commit_message" == *"destroy infra"* ]]; then
            echo "::set-output name=trigger_workflow::true"
          else
            echo "::set-output name=trigger_workflow::false"
          fi

  trigger_workflow:
    needs: check_commits
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow
        if: steps.check_commits.outputs.trigger_workflow == 'true'
        run: gh workflow run terraform-destroy.yaml


  # check_commit_message:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     - name: Check Commit Message
  #       id: commit_check
  #       run: |
  #         commit_message=$(git log --format=%B -n 1 ${{ github.sha }})
  #         echo "Commit Message: $commit_message"
  #         if [[ "$commit_message" == *"destroy infra"* ]]; then
  #           echo "Running Terraform Destroy Workflow"
  #           gh workflow run terraform-destroy.yaml
  #         else
  #           gh workflow run terraform.yaml 
  #         fi