name: Terraform Infra Workflow

on:
  push:
    branches:
      - master
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
env:
  TF_VERSION: 1.5.7
jobs:
  VPC-Infra-Terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: IAC-Files/demo/vpc
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS CLI
        run: |
          aws configure set default.region ${{ secrets.AWS_DEFAULT_REGION }}
          aws configure set default.output json

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Print assumed role
        run: aws sts get-caller-identity

      - name: Install Terragrunt
        run: |
          curl -Lo /tmp/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.45.16/terragrunt_linux_amd64
          chmod +x /tmp/terragrunt
          sudo mv /tmp/terragrunt /usr/local/bin/

      - name: Initialize Terragrunt
        run: terragrunt init

      - name: Terragrunt Plan
        run: terragrunt plan -out=vpctfplan

      - name: Terragrunt Apply
        run: terragrunt apply -auto-approve vpctfplan

  EKS-Infra-Terraform:
    runs-on: ubuntu-latest
    needs: VPC-Infra-Terraform
    defaults:
      run:
        working-directory: IAC-Files/demo/eks
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS CLI
        run: |
          aws configure set default.region ${{ secrets.AWS_DEFAULT_REGION }}
          aws configure set default.output json

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}

      - name: Install Terragrunt
        run: |
          curl -Lo /tmp/terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.45.16/terragrunt_linux_amd64
          chmod +x /tmp/terragrunt
          sudo mv /tmp/terragrunt /usr/local/bin/

      - name: Initialize Terragrunt
        run: terragrunt init

      - name: Terragrunt Plan
        run: terragrunt plan -out=ekstfplan

      # - name: Terragrunt Apply
      #   run: terragrunt apply -auto-approve ekstfplan





